### ISSUE TITLE
Update fails after Discord restart

### ISSUE THREAD

**Issue by FrzMtrsprt** [aliencaocao/netease_cloudmusic_discord_rpc#18]
After restarting Discord, update will fail with an `InvalidID` exception. The traceback is as follows.
```pytb
  File "...\pypresence\baseclient.py", line 81, in read_output
    preamble = await self.sock_reader.read(8)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [WinError 232] The pipe has been ended.

During handling of the above exception, another exception occurred:

  File "...\pypresence\baseclient.py", line 85, in read_output
    raise InvalidID
  File "...\pypresence\presence.py", line 34, in update
    return self.loop.run_until_complete(self.read_output())
  File "...\main.py", line 227, in update
    RPC.update(pid=pid,
  File "...\main.py", line 47, in _target
    self.function()
pypresence.exceptions.InvalidID: Client ID is Invalid
```
This is clearly pypresence's bug (see [#213](https://github.com/qwertyquerty/pypresence/issues/213)), and we'll have to wait for pypresence to fix this.

Below is a temporary fix.
```py
try:
    RPC.update(state="test")  # InvalidID after Discord restart
except InvalidID:
    print("Reconnecting")
    RPC.connect()  # RuntimeError: There is no current event loop in thread 'Thread-1 (_target)'.
```
Then we run into the second bug: `RuntimeError: There is no current event loop in thread 'Thread-1 (_target)'.`

It happened when `Presence` tries to renew the event loop in `connect()`, but fails to handle the exception when it can't find a existing one. 

This bug is fixed in [#210](https://github.com/qwertyquerty/pypresence/pull/210), which has been waiting for approval for two weeks.

**Comment by FrzMtrsprt** [comment]
I think it works for now.

**Comment by aliencaocao** [comment]
Great, then we can forget about upstream bugs
