### ISSUE TITLE
Support for beta client V3.0

### ISSUE THREAD

**Issue by aliencaocao** [aliencaocao/netease_cloudmusic_discord_rpc#24]
Netease just released a new beta client V3.0.0 build 201589 x64. I have found the offset total length but cant find the sound array within the whole cloudmusic.dll memory (using cheat engine full memory scan with unicode ticked). There are many instances of the song id in the entire scope (main exe+all DLLs) but I can't find one that reliably gives the song id. Most of them seem to partially give with 1 byte off (set to 0x00 when it should be in ASCII e.g. 0x30 onwards). I need some help with scanning the song array.

Besides, the current offset also cant be found. All those I found seem to be static, they don't update as the song plays. I think they upgraded their anti-debugging feature.

Tagging original contributor of song array feature @lekoOwO and RE expert @twinklestar03

**Comment by lekoOwO** [comment]
You might be interested in BetterNCM

**Comment by aliencaocao** [comment]
update: found length and current offsets: https://github.com/aliencaocao/netease_cloudmusic_discord_rpc/commit/65481787c650b094dbe24ff04e59f3705fe2c620
song array does not seem to be in `cloudmusic.dll` anymore

**Comment by aliencaocao** [comment]
found multi-level pointers in cloudmusic.dll that points to song id, but the offsets changes every song, so far I don't have a good way to find out the offsets unless I run cheat engine on every song.
Maybe need a better way of fetching the current song info.

**Comment by aliencaocao** [comment]
Resolved in https://github.com/aliencaocao/netease_cloudmusic_discord_rpc/commit/028ddf26778d57f7e1073c2325124fcb53f70fe9
Latest V0.3.0 supports V3.0 beta clients
