### ISSUE TITLE
V0.3.0 regression with V2.x clients

### ISSUE THREAD

**Issue by aliencaocao** [aliencaocao/netease_cloudmusic_discord_rpc#29]
### Discussed in https://github.com/aliencaocao/netease_cloudmusic_discord_rpc/discussions/28
<sup>Originally posted by **JdumB** October 24, 2023</sup>

TLDR of discussion: V0.2.8 works, V0.3.0 does not work for client V2.10.11. To test on client V2.10.12.

**Comment by aliencaocao** [comment]
Hi @JdumB please try https://github.com/aliencaocao/netease_cloudmusic_discord_rpc/releases/tag/0.3.1 and see if it works for you on the latest V2.10.12 client.

**Comment by JdumB** [comment]
Sry for the late reply. Yes, it's working. Thanks pal, appreciate your hard
work.
[image: image.png]
