### ISSUE TITLE
功能建议：托盘图标和开关UI

### ISSUE THREAD

**Issue by EagleZhen** [aliencaocao/netease_cloudmusic_discord_rpc#31]
1. 弄一个托盘显示或许会比较方便操作一些
2. 还有就是如果有其它也支持Discord RPC的进程在运行的时候，可不可以也暂时关闭？像是[旧版本的那个](https://github.com/Kxnrl/NetEase-Cloud-Music-DiscordRPC)其实也有个软件白名单

**Comment by aliencaocao** [comment]
> 弄一个托盘显示或许会比较方便操作一些

这个会添加到已计划功能中

> 还有就是如果有其它也支持Discord RPC的进程在运行的时候，可不可以也暂时关闭？像是[旧版本的那个](https://github.com/Kxnrl/NetEase-Cloud-Music-DiscordRPC)其实也有个软件白名单

关于这个，我不想采用白名单的方式，因为添加正确的程序名称和可执行文件路径需要一定的电脑知识。我计划做一个简单的Tkinter UI，里面允许用户自行开关。
但是当多个RPC在运行的时候，Discord的政策是第一个开始运行的优先，这点我们不能控制，所以还要用户自行关闭其他的RPC才可以看到这个的效果。

**Comment by aliencaocao** [comment]
Fixed in https://github.com/aliencaocao/netease_cloudmusic_discord_rpc/commit/f262036ac010852fb9ed8baf850ceb9326dff1bf
UI和托盘均已实现，请下载[最新版本](https://github.com/aliencaocao/netease_cloudmusic_discord_rpc/releases/tag/0.3.3)试用。
