### ISSUE TITLE
RPC应用最小化时discord歌曲状态不会实时更新

### ISSUE THREAD

**Issue by Panrium** [aliencaocao/netease_cloudmusic_discord_rpc#37]
当PRC窗口在右下角后台运行（被最小化至托盘或者关闭窗口）时，歌曲状态不会实时更新，比如网易云一首歌放完了换到下一首歌时 discord界面不会切换歌曲，且显示时长会超过原本歌曲长度继续往下计时。此时从托盘图标点开窗口才会继续同步实时歌曲信息。

而当PRC窗口没有被关闭，还显示在任务栏时就一切正常
![image](https://github.com/user-attachments/assets/47d9a09e-c5c5-46a8-89b0-23e1025b03ef)

**Comment by aliencaocao** [comment]
你是用的哪个版本，试过最新版0.3.5吗？

**Comment by Panrium** [comment]
是的, 0.3.5,
网易云版本2.10.13(Build:202675)(Patch:1:2acb09d)
win11系统

**Comment by aliencaocao** [comment]
可以在exe旁边创建一个debug.log空文件，然后再触发下bug看看。我需要看看日志

**Comment by Panrium** [comment]
![image](https://github.com/user-attachments/assets/3ba279c9-e66d-4933-8654-13f500381582)
我播放了这个专辑，从第一首歌Feeling开始放的时候，把PRC窗口关闭（右下角托盘运行）， 放到第四首歌（pouring)的时候discord界面还是在显示第一首歌，如下：
![image](https://github.com/user-attachments/assets/44fe9ac6-70bd-4e3d-b7ce-33bbb7c22c8b)

然后从托盘点开PRC窗口，窗口显示了半秒第二首歌的标题（dolls)，然后变成了当前播放的第四首。再去看discord也正常同步了。此时debug文件如下
![image](https://github.com/user-attachments/assets/5d5a5dda-45b8-4758-9e57-abd184dd2d6b)

**Comment by aliencaocao** [comment]
OK 我去调查一下原因

**Comment by SuperWildFireFox** [comment]
的确是有这个问题

**Comment by minghe-cwrs** [comment]
有没有考虑过加大进程优先级？

**Comment by aliencaocao** [comment]
已在最新版[0.3.6](https://github.com/aliencaocao/netease_cloudmusic_discord_rpc/releases/tag/0.3.6)中修复
